### ISSUE TITLE
Shortcode to generate button-list with available cities to filter on

### ISSUE THREAD

**Issue by itssimple** [MultinetInteractive/EduAdmin-WordPress#101]
This should only be used in list views, because we won't build in a ajax-filter possibility for event views on detail pages.

If that is needed, we need to create another shortcode.

**Comment by BFwebb** [comment]
You should also do the same for the parameter Regions. +1 for priority om this feature

**Comment by itssimple** [comment]
@BFwebb I created another issue for tracking that request. #109
