### ISSUE TITLE
In the course list (events), specify how many events you want to show

### ISSUE THREAD

**Issue by itssimple** [MultinetInteractive/EduAdmin-WordPress#13]
`[eduadmin-listview numberofevents="6"]` should show six events, if the plugin is set to show events, otherwise the attribute will be ignored

**Comment by karllindval** [comment]
Hi, I've tried to make this work but unfortunately nothing changes.

This is the code I'm using, let me know if any changes need to be done to it!

<?php echo do_shortcode('[eduadmin-listview hidesearch numberofevents="6"]')?>

**Comment by itssimple** [comment]
The attribute have not been implemented yet. I hope I'll have this done this week.

**Comment by karllindval** [comment]
Hi, is it possible to use <?php echo do_shortcode('[eduadmin-listview hidesearch numberofevents="6"]')?> now or is this feature still in the making?

**Comment by itssimple** [comment]
It depends what version you have. It should be in the [0.9.9.2.5](https://github.com/MultinetInteractive/EduAdmin-WordPress/releases/tag/v0.9.9.2.5)-version.

Although, I'm not certain of the markup. This is the first plugin I've written, so I cannot say if the `do_shortcode`-thing works. I haven't tried that myself.
