### ISSUE TITLE
Error when rendering list with search form

### ISSUE THREAD

**Issue by akeblom** [MultinetInteractive/EduAdmin-WordPress#139]
Just updated to the latest version. Getting this error when rendering a list:

<b>Fatal error</b>:  Cannot use object of type stdClass as array in <b>/dev/customer/wordpress/wp-content/plugins/eduadmin-booking/content/template/listTemplate/search-form.php</b> on line <b>40</b><br />v

**Comment by itssimple** [comment]
@akeblom Have you tried go into the General Settings and clear the cache? It might be old data stored in the cache of the plugin that needs to be cleared since we're beginning to convert to the new API.

**Comment by akeblom** [comment]
Yup, that worked well. Thanks!
