### ISSUE TITLE
Checkbox to save invoice info in customer database and not just on booking

### ISSUE THREAD

**Issue by pmerkland-mn** [MultinetInteractive/EduAdmin-WordPress#219]
This only applies to when signing in before booking a course. The first time a visitor book a course the checkbox should be hidden. Next time when signing in and booking a course the checkbox gives to option to replace the invoice info.

**Comment by itssimple** [comment]
ping @MNKevin

This will be a setting that our customer must activate, to allow their end customers to update their customer profile while they are booking themselves.

And when this setting is activated, end customers will have a checkbox in the booking form, that says something in the likes of _"Also update my customer information for future use"_
