### ISSUE TITLE
Setting to hide all texts regarding VAT

### ISSUE THREAD

**Issue by mn-osal** [MultinetInteractive/EduAdmin-WordPress#228]
Requested by a customer. 

As all education is exempt from VAT in Norway (customer sent this as a reference: https://miniforetak.no/okonomi/undervisning-er-momsfri-men-ikke-informasjon) they do not want any text about "incl. VAT" or "excl. VAT" in the detail view, list view or booking form.

**Comment by itssimple** [comment]
New setting found under `General settings` from version `2.7.1`
