### ISSUE TITLE
Price calculation should always start at 1 x participant even if name fields are emtpy

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#236]
It is confusing when the price is zero. We should always show at least the price for one participant.

**Comment by pmerkland** [comment]
Tror inte detta fungerar.

**Comment by itssimple** [comment]
Apparently not, since another thing was added to skip price checks if the customers want to use the contact person as a participant as well (to avoid double prices).

But this fix apparently made it so that no price was added at all.
