### ISSUE TITLE
Provide translation of back-end and front-end in separate lang files in WP

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#241]
Most customers only want to translate their front-end. If we put back-end and front-end strings in seperate files that would be possible.

Now all string are in the same list så there is really no way of knowing what you are translating.

**Comment by itssimple** [comment]
We don't provide files for translation, we use the standard WordPress code for translations.
Which means that translations are downloaded from WordPress when they install the plugin.

And I'm not sure that changing how we translate things will affect the current translations.
We'll be losing all the translation we've already done.

> If you're translating a plugin or a theme, you'll need to use a text domain to denote all text belonging to that plugin. This increases portability and plays better with already existing WordPress tools. The text domain must match the “slug” of the plugin.
>
>The Text Domain needs to be added to the plugin header. WordPress should internationalize your plugin or theme meta-data when it displays your plugin in the admin screens

https://codex.wordpress.org/I18n_for_WordPress_Developers#Text_Domains

**Comment by pmerkland** [comment]
You could just have said no :)

**Comment by itssimple** [comment]
I have added context to all phrases in the plugin.

Which also reset the translation for 90% of the plugin. But I'm almost done translating everything again!

**Comment by itssimple** [comment]
There should now be a possibility to filter on context, where we have `backend` and `frontend`
