### ISSUE TITLE
Show the same layout for coursedays, both with continuous dates with the same start and end time and with different times

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#254]
Show the same layout for coursedays, both with continuous dates with the same start and end time and with different times

If the start and end time of two course days are the same, we print "mon 8 - tue 9, 08:00-16:00"

If the start and end time differ we show a button with a popup layer with: 
"mon 8, 08:01-16:00"
"tue 9, 08:00-16:00"

If we have to choose one of these I would go with the popup because that will support longer lists with coursedays.

**Comment by itssimple** [comment]
So, do you mean that you want it to be possible, to show all days separately, even if they are connected?

**Comment by pmerkland** [comment]
> So, do you mean that you want it to be possible, to show all days separately, even if they are connected?

Correct.
