### ISSUE TITLE
Mandatory questions are missing validation and crashes the booking

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#268]
If you use the settings in EduAdmin to make certain questions on participants for example mandatory and the customer skips them and tries to book the site crashes. We should fix this by adding validation to the mandatory questions.

**Comment by pmerkland** [comment]
Helpdesk issue 23321 should be answered when fix is published.

**Comment by itssimple** [comment]
The problem is that PHP doesn't send inputs that are empty, so I will have to rebuild this to work in another way. And always send required fields. The API should handle this in a better way.

**Comment by pmerkland** [comment]
JavaScript validation?

V?nligen,
Per Merkland




On Wed, Jul 3, 2019 at 5:25 PM +0200, "Chris G?rdenberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


The problem is that PHP doesn't send inputs that are empty, so I will have to rebuild this to work in another way. And always send required fields. The API should handle this in a better way.

-

**Comment by itssimple** [comment]
Yeah, it crashes when it's trying to calculate the price, which breaks validation, that is used in javascript. That's why I have to rewrite it, so it always sends required fields to the API.

But it's not something I'm gonna do during my vacation :)

**Comment by itssimple** [comment]
Apparently only happens when you select that the *Customer contact* also is a participant.
