### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by itssimple** [MultinetInteractive/EduAdmin-WordPress#28]
Provide an easy way to make it possible to use multiple translations

If possible, see if it is possible to integrate with other translation plugins.

**Comment by slackday** [comment]
Just add a default language file for english. All strings already seem to use `i18n` https://codex.wordpress.org/I18n_for_WordPress_Developers

Users can translate and make PRs with new/updated language files if needed.

My opinion is that string-translation and language file generation is out of scope for this plugin. There's plenty of plugins, many free, for translating.

**Comment by itssimple** [comment]
I have a default file for english (stored in `defaultPhrases.json`), but I know it isn't using the "normal" WordPress-way to provide translations.

This is mainly because we had wishes to be able to translate directly from the plugin.

But I'll look into replacing it (if applicable), I have to make sure that it works with already translated plugins. :)
