### ISSUE TITLE
Add unique classes to the body tag for the course pages

### ISSUE THREAD

**Issue by mrswanberg** [MultinetInteractive/EduAdmin-WordPress#297]
If you could add a unique class on each page that is generated (eg the occasion number) on the **body**-tag so that you can target classes for a specific course / page.
Like WP does with _page-id_.

**Comment by itssimple** [comment]
I'm not sure that we can control the body-tag on the page, since the user/customer only adds a shortcode to the page. But I can check the possibility to add it to the wrapper-div-element instead.
