### ISSUE TITLE
Setting to allow changing the event ID at all times on the booking form

### ISSUE THREAD

**Issue by mrswanberg** [MultinetInteractive/EduAdmin-WordPress#300]
When you go to the booking page without an event ID and select a date / time in the list, it locks. It is not possible to change without reversing and returning again.

**Comment by itssimple** [comment]
This is the intended way to handle it.

If you don't provide the event ID, you're able to select one, and then it will be locked to that event ID.

But I guess that this is a request to set, so that you can change afterwards as well, so I'll add the appropriate label.
