### ISSUE TITLE
Filter deeper when retrieving events with a filter on category

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#303]
When using [eduadmin-listview mode="event" category="xxxxx"] you only get the events for courses in this category and not its subcategories. To also include subcategories would be preferable.
EduAdmin API is now updated to enable deeper filtering on category when getting events.

odata/Events?$filter=Categories/any(c:c/CategoryId eq xxxxxx)

**Comment by pmerkland** [comment]
[eduadmin-listview mode="event" category-deep="xxxxx"] or [eduadmin-listview mode="event" category-sub="xxxxx"] or [eduadmin-listview mode="event" category-all="xxxxx"] ? :)

**Comment by itssimple** [comment]
Attribute will be named `categorydeep`.

Will also be possible to write `deep-<categoryid>` in the `category`-attribute as well.
