### ISSUE TITLE
Double participant when autofill via the browser

### ISSUE THREAD

**Issue by mrswanberg** [MultinetInteractive/EduAdmin-WordPress#317]
When you fill in the booking form and you choose to autofill via the browser (eg Chrome) and the field for participants is filled and then after you have filled in the contact person and the option "I am also a participant" it becomes a double participant. This is because the auto-filled field is seen as person # 2.

**Comment by itssimple** [comment]
I have disabled all the autocompletion that I could find fields for.

This has to be tested on our own demo instance first, before we release it.
