### ISSUE TITLE
Booking page shows errors

### ISSUE THREAD

**Issue by madde1** [MultinetInteractive/EduAdmin-WordPress#377]
When you go to the booking page with out booking a course it shows, it was not like that before update :
Warning: count(): Parameter must be an array or an object that implements Countable in /home/seodokto/eduperformance.seo-doktorn.se/wp-content/plugins/eduadmin-booking/content/template/bookingTemplate/course-info.php on line 26
Warning
: count(): Parameter must be an array or an object that implements Countable in
/home/seodokto/eduperformance.seo-doktorn.se/wp-content/plugins/eduadmin-booking/content/template/bookingTemplate/event-selector.php
on line
24

Warning
: count(): Parameter must be an array or an object that implements Countable in
/home/seodokto/eduperformance.seo-doktorn.se/wp-content/plugins/eduadmin-booking/content/template/bookingTemplate/event-selector.php
on line

**Comment by itssimple** [comment]
Seems like the data returned from the EduAdmin API doesn't contain any events.

**Comment by madde1** [comment]
Fixed it with empty() function instead of count..
