### ISSUE TITLE
Change behavior of the Book button when accessing the form without an event i.e. /book/

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#405]
When nothing is selected in the dropdown the text on the button should always be "Book" or maybe "You must first select an event". 

The problem is if nothing is selected in the dropdown the Book button will show a text based on the first event in the dropdown, i.e. if that event is fully booked then the button will show that text which is confusing.

**Comment by itssimple** [comment]
Solving this by filtering the available events, to events that only can be booked (have spots left), and by selecting the first available event in the dropdown.
