### ISSUE TITLE
Google Analytics not able to track information such as purchases from the EduAdmin standard forms when the form is hosted on a website using EduAdmin WordPress-plugin

### ISSUE THREAD

**Issue by ghost** [MultinetInteractive/EduAdmin-WordPress#412]
When tracking (more specifically Google Analytics) is enabled on the EduAdmin standard forms, not all information get shared with the service that tracks the form.

For instance the information about income from the standard form is only sent to Google Analytics if the website hosting the form has a JavaScript that is designed to send that information to Google Analytics.

Tracking for the standard forms was developed with the web portal in mind which is why the web portal has that kind of JavaScript that retrieves the information about income among other things from the standard form and sends it to the tracking service.

My suggestion is to implement something similar into the EduAdmin WordPress-plugin to enable users to track information from the standard form even if their website is using WordPress and not the web portal.

**Comment by itssimple** [comment]
Asked one of the developers that know how to integrate with the standard forms.
We need to listen to javascript messages that is sent through `window.parent.postMessage`, with specific types.

So if we can figure out what type of messages that we receive, we could make a better possibility for the plugin users, to track booking/purchases through services like Google Analytics.

The types that we know about are:
- `eduadmin-pageview`
- `eduadmin-booking-form-loaded`
- `eduadmin-order` (This is probably the one sent when the order is completed)
