### ISSUE TITLE
The setting "Show headers in detail view" should have an effect on detail views for programmes as well

### ISSUE THREAD

**Issue by mn-osal** [MultinetInteractive/EduAdmin-WordPress#414]
It should affect courses and programmes in exactly the same way. Right now it only hides/shows headers on coursetemplates, not programmes.

![image](https://user-images.githubusercontent.com/32517718/148748223-e2bc8632-7fe2-40cd-82ad-fad5cf5ef69c.png)

**Comment by itssimple** [comment]
The setting clearly says "course detail view" though. But I can make so it also affects the programme details.

**Comment by mn-osal** [comment]
> The setting clearly says "course detail view" though. But I can make so it also affects the programme details.

You're very right, I missed that. :') Changed the title to reflect that this is a feature request and not a bug.
