### ISSUE TITLE
Excel export from the Booking list and certificate list on "My profile"

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#426]

**Comment by itssimple** [comment]
Any idea on how the format would be? I feel like I need a bit more information on what the export should contain, or if there should be any options on what to export.

Or just basically, the tables available on that page, in that format?

**Comment by itssimple** [comment]
Should the export, export everything in a single file, or should we allow for exporting single courses/events?

**Comment by pmerkland** [comment]
Hmm, both?
