### ISSUE TITLE
Add a sort feature to the Booking list on "My profile"

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#427]
Now the default order is by Created date for the booking. To be able to sort on Event Startdate would also be practical.

**Comment by MastodontMedia** [comment]
På rad 33 i filen content/template/myPagesTemplate/bookings.php behöver ni lägga in följande:

apply_filters( 'edu_bookings', $bookings );

**Comment by itssimple** [comment]
> På rad 33 i filen content/template/myPagesTemplate/bookings.php behöver ni lägga in följande:
> 
> apply_filters( 'edu_bookings', $bookings );

Will add that, so that external plugins/code can customize the sorting as well. Thanks for the suggestion!

**Comment by MastodontMedia** [comment]
> > På rad 33 i filen content/template/myPagesTemplate/bookings.php behöver ni lägga in följande:
> > apply_filters( 'edu_bookings', $bookings );
> 
> Will add that, so that external plugins/code can customize the sorting as well. Thanks for the suggestion!

When can we expect this to be added?

**Comment by itssimple** [comment]
About.. 10 minutes? :)
