### ISSUE TITLE
Add support for the new date value for when an event is open for registrations

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#436]
This means showing a text phrase and the date/time instead of Book buttons where applicable.
"Opens for registration 2022-04-01 10:00"

Also, the booking form will probably have to check for this as well and show a message similar to above and block registrations.

The date will soon show on Events in the API.

**Comment by itssimple** [comment]
@pmerkland Should we have a setting, to allow users/customers to choose how `ApplicationOpenDate` should work.

For instance
- Hide events, where the date hasn't passed yet
- Show event, but replace button with date

Maybe something more?

**Comment by pmerkland** [comment]
I am not certain we need a setting, but if we do the default should be "Show event, replace button with date" in my opinion.

**Comment by itssimple** [comment]
I'll start without a setting, so we can add it later on.

**Comment by itssimple** [comment]
![image](https://user-images.githubusercontent.com/11502257/187850427-91abdde8-0396-4a9d-a204-97961be10177.png)

Something like this then? @MNKevin

Or like this?
![image](https://user-images.githubusercontent.com/11502257/187851419-e45c6575-a1d2-476f-8c4d-777ccc094215.png)

**Comment by pmerkland** [comment]
English:
Application opens
date-with-datuminställningar-format
Swedish:
Anmälan öppnar
date-with-datuminställningar-format

**Comment by itssimple** [comment]
> English: Application opens date-with-datuminställningar-format Swedish: Anmälan öppnar date-with-datuminställningar-format

So, add a setting, so that the customer can choose between the three then?

**Comment by pmerkland** [comment]
> > English: Application opens date-with-datuminställningar-format Swedish: Anmälan öppnar date-with-datuminställningar-format
> 
> So, add a setting, so that the customer can choose between the three then?

No, follow the settings that already exist for detailview and listview.

**Comment by pmerkland** [comment]
![image](https://user-images.githubusercontent.com/21121350/187855058-7a9f93e6-8648-4ffd-a7e3-37d2cdf454a8.png)

**Comment by itssimple** [comment]
![image](https://user-images.githubusercontent.com/11502257/187856644-9caacfbe-959b-42b1-bef7-6a628a4316f0.png)

**Comment by pmerkland** [comment]
Maybe hide ", time" if the value is 00:00?

**Comment by itssimple** [comment]
> Maybe hide ", time" if the value is 00:00?

Since it's a timezone thing, I'm gonna say no to this.

**Comment by MNKevin** [comment]
> Maybe hide ", time" if the value is 00:00?

My guess is that if you're not actively choosing any application open time (defaulting to 00:00) on an event you either want the time to be visible or you never care about the time, only the date.

Since you're able to hide the time using either the Date Settings in the plugin or CSS, I agree with itssimple.
We shouldn't add any code to automatically hide the time based on the shown value.

Setting:
![bild](https://user-images.githubusercontent.com/24244669/187862548-f726f2eb-f782-4931-9522-27f53a5c8507.png)

CSS: (class="applicationOpenTime")
![bild](https://user-images.githubusercontent.com/24244669/187860129-a823f4b3-a8a0-4893-a117-03484a60109f.png)

**Comment by itssimple** [comment]
Exactly how it works currently, as I added it in accordance to follow the settings, as we said.
