### ISSUE TITLE
Listview-shortcode: order(-by)-attribute

### ISSUE THREAD

**Issue by itssimple** [MultinetInteractive/EduAdmin-WordPress#45]
Ability to apply custom sorting to the listview

`[eduadmin-listview orderby="PeriodStart CategoryName" order="ASC ASC"]`

In event-lists the following properties (case insensitive) will be sortable:
`categoryid`, `categoryname`, `city`, `description`,
`educationlevelid`, `eventid`, `lastapplicationdate`,
`locationaddressid`, `locationid`, `objectid`, `objectname`,
`occationid`, `parenteventid`, `periodend`, `periodstart`,
`regionid`, `seats`, `showonweb`, `showonwebinternal`,
`statusid`, `statustext`

In the course-lists the following properties (case insensitive) will be sortable:
`objectid`, `objectname`, `showonweb`, `showonwebinternal`
`categoryid`, `itemnr`, `requirecivicregistrationnumber`,
`coursedescription`, `coursedescriptionshort`, `publicname`,
`coursegoal`, `targetgroup`, `prerequisites`, `courseafter`,
`quote`, `department`, `maxparticipantnr`, `minparticipantnr`,
`categoryname`, `sortindex`, `educationlevelid`, `shortening`

**Comment by slackday** [comment]
Sort value looks arbitrary could you list available options somewhere please?

**Comment by slackday** [comment]
Would it be possible to follow core Wordpress attribute syntax?

`[eduadmin-listview orderby="PeriodStart" order="ASC"]`

**Comment by itssimple** [comment]
Yeah, I'm gonna write a list with available properties (In the Wiki and here, when I have time to do that)
Just adding some placeholder issues, so I can start coding and then update the issue when I know what I want to support. :)

Does Wordpress support multiple sort expressions? I'm planning on handling multiple expressions by comma separating them.

**Comment by slackday** [comment]
I updated my first comment. Thought this was a merge... sorry about that I jumped to conclusion.

Wordpress supports multiple sort expressions as string separated by space. 

`[eduadmin-listview orderby="PeriodStart CourseTitle" order="ASC ASC"]`

or array if using objects

```
new WP_Query([
'orderby' => ['date', 'title'],
'order' => ['ASC, 'ASC'],
]);
```

**Comment by itssimple** [comment]
Updated title and description. Currently coding. ^^

**Comment by itssimple** [comment]
I have tried some of the properties and it seems to work.
