### ISSUE TITLE
Create a keyword to get the program image

### ISSUE THREAD

**Issue by mrswanberg** [MultinetInteractive/EduAdmin-WordPress#506]
Similar to the `[eduadmin-detailinfo courseimage]`

Example: `[eduadmin-programmeinfo programmeimage]`

**Comment by itssimple** [comment]
Will create something like `[eduadmin-programmeinfo]` which will work a lot like `[eduadmin-detailinfo]`, but for programmes instead.

Attributes may differ depending on what support we have in the API.
