### ISSUE TITLE
Settings to choose which fields that are required/visible in the booking form.

### ISSUE THREAD

**Issue by maan2** [MultinetInteractive/EduAdmin-WordPress#82]
Should be implemented, since many customers ask for this.

For example, organization number, email and so on.
(Look at booking forms in EduAdmin on how to make this)

**Comment by itssimple** [comment]
We're still discussing internally how to handle this.

**Comment by pmerkland** [comment]
This stuff is being requested again and again ....

**Comment by itssimple** [comment]
Yes, and it still has to be fixed inside EduAdmin first.

**Comment by andersjonsson** [comment]
Closing.
Will be fixed by #381
