### ISSUE TITLE
Hide "Quote" in detailinfo-page

### ISSUE THREAD

**Issue by maan2** [MultinetInteractive/EduAdmin-WordPress#84]
This field is only used internally in EduAdmin

**Comment by itssimple** [comment]
We need to discuss this before hiding an actual field that is used by customers.

Maybe there could be a settings to show/hide fields instead of hiding them for everyone.

**Comment by itssimple** [comment]
I have an idea.

Let's make an attribute, that takes a comma separated list of fields you want to hide.

Like this: `[eduadmin-detailview hide="quote,price"]`

**Comment by itssimple** [comment]
Fields that can be hidden:
- description
- goal
- target
- prerequisites
- after
- quote

**Comment by BFwebb** [comment]
Is it possible to also hide price and time? The price can differ between different locations and the time can differ. Now it shows as a confusing information. We want it to show only after pressing the"booking"-button.

**Comment by itssimple** [comment]
Additional fields to hide
- [ ] price
- [ ] time

Note that the time will not be hidden from the event list, only the describing fields above the list.

**Comment by BFwebb** [comment]
Tnx for Quick fix! But... how should the syntax be? [eduadmin-detailview hide="quote, price, time"] seems not to hide price ande time, but quote. (Yes upgrade is installed)

**Comment by itssimple** [comment]
`[eduadmin-detailview hide="quote,price,time"]` would be the syntax. I forgot to trim additional whitespace when I split the attribute.

**Comment by BFwebb** [comment]
Thanks, working fine now, but the page is currently a bit slow... not related to the filtering though...
https://bfmitt.se/bokning/heta-arbeten__411826/

**Comment by itssimple** [comment]
Yeah.. I noticed that after I switched to WordPress own Ajax-API, everything went real slow. But locally I only went up with 3 seconds for the ajax-requests. But it seems on your site that even the initial visit takes about 27 seconds. I'll see if I can find out what's causing this.
